// AUTO-GENERATED by scripts/gen_event_types.py — DO NOT EDIT BY HAND.
// Source of truth: api/models.py (Pydantic event models).
// Regenerate: python scripts/gen_event_types.py
// CI guard:   python scripts/gen_event_types.py --check
// Generated:  2026-05-06

// JSDoc @typedef block consumed by the extension's
// vanilla-JS source. Use as:  /** @type {import('./event-types').TokenEvent} */

/**
 * @typedef {(
 *   "token" |
 *   "thinking" |
 *   "thinking_end" |
 *   "workflow_start" |
 *   "workflow_done" |
 *   "step_start" |
 *   "step_done" |
 *   "loop_iteration" |
 *   "condition_eval" |
 *   "map_item" |
 *   "retry_attempt" |
 *   "retry_backoff" |
 *   "retry_notice" |
 *   "tool_call" |
 *   "tool_result" |
 *   "variable_set" |
 *   "memory_update" |
 *   "compaction" |
 *   "validation_warning" |
 *   "done" |
 *   "error" |
 *   "cancelled" |
 *   "chat_title" |
 *   "chat_list" |
 *   "session_info" |
 *   "profile_info" |
 *   "profile_switch_done" |
 *   "settings_info" |
 *   "pet_changed" |
 *   "extension_status" |
 *   "reset_done" |
 *   "approval_required" |
 *   "shell_process_start" |
 *   "shell_output" |
 *   "shell_process_done" |
 *   "ext_chat_start" |
 *   "ext_chat_turn" |
 *   "ext_chat_error" |
 *   "ext_chat_done" |
 *   "ping" |
 *   "pong"
 * )} EventTypeName
 */

/**
 * @typedef {Object} CompactionEvent
 * @property {string} type [optional]
 * @property {number} removed
 * @property {number} kept
 * @property {string} summary_preview [optional]
 */

/**
 * @typedef {Object} ConditionEvalEvent
 * @property {string} type [optional]
 * @property {string} step_id
 * @property {*} condition
 * @property {boolean} result
 */

/**
 * @typedef {Object} DoneEvent
 * @property {string} type [optional]
 */

/**
 * @typedef {Object} ErrorEvent
 * @property {string} type [optional]
 * @property {string} message
 * @property {string | null} step_id [optional]
 */

/**
 * @typedef {Object} LoopIterationEvent
 * @property {string} type [optional]
 * @property {string} step_id
 * @property {number} iteration
 * @property {number} max
 */

/**
 * @typedef {Object} MapItemEvent
 * @property {string} type [optional]
 * @property {string} step_id
 * @property {number} index
 * @property {number} total
 */

/**
 * @typedef {Object} MemoryUpdateEvent
 * @property {string} type [optional]
 * @property {string} key
 * @property {string} value
 */

/**
 * @typedef {Object} RetryAttemptEvent
 * @property {string} type [optional]
 * @property {string} step_id
 * @property {number} attempt
 * @property {number} max
 */

/**
 * @typedef {Object} StepDoneEvent
 * @property {string} type [optional]
 * @property {string} step_id
 * @property {number} duration_ms
 */

/**
 * @typedef {Object} StepStartEvent
 * @property {string} type [optional]
 * @property {string} step_id
 * @property {string} step_type
 * @property {string | null} workflow_id [optional]
 */

/**
 * @typedef {Object} TokenEvent
 * @property {string} type [optional]
 * @property {string} text
 */

/**
 * @typedef {Object} ToolCallEvent
 * @property {string} type [optional]
 * @property {string} step_id
 * @property {string} tool
 * @property {Record<string, *>} args
 */

/**
 * @typedef {Object} ToolResultEvent
 * @property {string} type [optional]
 * @property {string} step_id
 * @property {string} tool
 * @property {*} result
 * @property {string | null} error [optional]
 * @property {number} duration_ms
 */

/**
 * @typedef {Object} VariableSetEvent
 * @property {string} type [optional]
 * @property {string} name
 * @property {string} var_type
 * @property {number} size_bytes
 * @property {string} value_preview [optional]
 */

/**
 * @typedef {Object} WorkflowDoneEvent
 * @property {string} type [optional]
 * @property {string} workflow_id
 * @property {Record<string, *>} variables
 */

/**
 * @typedef {Object} WorkflowStartEvent
 * @property {string} type [optional]
 * @property {string} workflow_id
 * @property {string} name
 */

/**
 * @typedef {(CompactionEvent | ConditionEvalEvent | DoneEvent | ErrorEvent | LoopIterationEvent | MapItemEvent | MemoryUpdateEvent | RetryAttemptEvent | StepDoneEvent | StepStartEvent | TokenEvent | ToolCallEvent | ToolResultEvent | VariableSetEvent | WorkflowDoneEvent | WorkflowStartEvent)} EngineEvent
 */

// Module marker so this file can be imported as a side-effect
// from typed JSDoc consumers without complaints.
export {};
