#!/usr/bin/env python3
"""
Chika — interactive setup wizard.
Run: python install.py
"""

import sys
import os
import subprocess
import shutil
import getpass
import textwrap
from pathlib import Path

ROOT = Path(__file__).parent

# ── ANSI colours ──────────────────────────────────────────────────────────────

RESET  = "\033[0m"
BOLD   = "\033[1m"
DIM    = "\033[2m"
RED    = "\033[91m"
GREEN  = "\033[92m"
YELLOW = "\033[93m"
BLUE   = "\033[94m"
CYAN   = "\033[96m"
WHITE  = "\033[97m"

def c(color: str, text: str) -> str:
    return f"{color}{text}{RESET}"

def ok(msg: str)   -> None: print(f"  {c(GREEN,  '✓')}  {msg}")
def err(msg: str)  -> None: print(f"  {c(RED,    '✗')}  {msg}")
def info(msg: str) -> None: print(f"  {c(BLUE,   '·')}  {msg}")
def warn(msg: str) -> None: print(f"  {c(YELLOW, '!')}  {msg}")
def step(n: int, total: int, msg: str) -> None:
    print(f"\n{c(BOLD+WHITE, f'[{n}/{total}]')} {c(BOLD, msg)}")

def rule(char: str = "─", width: int = 60) -> None:
    print(c(DIM, char * width))

def banner() -> None:
    print()
    print(c(BOLD + CYAN, "  ██████╗██╗  ██╗██╗██╗  ██╗ █████╗ "))
    print(c(BOLD + CYAN, " ██╔════╝██║  ██║██║██║ ██╔╝██╔══██╗"))
    print(c(BOLD + CYAN, " ██║     ███████║██║█████╔╝ ███████║"))
    print(c(BOLD + CYAN, " ██║     ██╔══██║██║██╔═██╗ ██╔══██║"))
    print(c(BOLD + CYAN, " ╚██████╗██║  ██║██║██║  ██╗██║  ██║"))
    print(c(BOLD + CYAN, "  ╚═════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚═╝  ╚═╝"))
    print()
    print(c(DIM, "  Agentic AI assistant with browser control"))
    print(c(DIM, "  github.com/tochi-mba/chika"))
    print()
    rule()
    print()

# ── Helpers ───────────────────────────────────────────────────────────────────

def ask(prompt: str, default: str = "") -> str:
    suffix = f" [{c(DIM, default)}]" if default else ""
    val = input(f"  {c(CYAN, '?')}  {prompt}{suffix}: ").strip()
    return val or default

def ask_secret(prompt: str) -> str:
    return getpass.getpass(f"  {c(CYAN, '?')}  {prompt}: ")

def ask_choice(prompt: str, choices: list[tuple[str, str]], default: int = 1) -> str:
    """Display a numbered menu and return the chosen value."""
    print(f"\n  {c(BOLD, prompt)}")
    for i, (key, label) in enumerate(choices, 1):
        marker = c(CYAN, "▶") if i == default else " "
        print(f"    {marker} {c(BOLD, str(i))}.  {label}")
    print()
    while True:
        raw = input(f"  {c(CYAN, '?')}  Enter number [{c(DIM, str(default))}]: ").strip()
        if not raw:
            return choices[default - 1][0]
        if raw.isdigit() and 1 <= int(raw) <= len(choices):
            return choices[int(raw) - 1][0]
        warn("Please enter a valid number.")

def ask_yn(prompt: str, default: bool = True) -> bool:
    hint = c(DIM, "Y/n" if default else "y/N")
    raw = input(f"  {c(CYAN, '?')}  {prompt} [{hint}]: ").strip().lower()
    if not raw:
        return default
    return raw in ("y", "yes")

def run(cmd: list[str], capture: bool = False) -> subprocess.CompletedProcess:
    kwargs: dict = {"check": True}
    if capture:
        kwargs.update(stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    return subprocess.run(cmd, **kwargs)

# ── Steps ─────────────────────────────────────────────────────────────────────

TOTAL_STEPS = 5

def check_python() -> None:
    step(1, TOTAL_STEPS, "Checking Python version")
    major, minor = sys.version_info[:2]
    if (major, minor) < (3, 11):
        err(f"Python 3.11+ required — you have {major}.{minor}")
        sys.exit(1)
    ok(f"Python {major}.{minor}")

    if not shutil.which("pip"):
        err("pip not found. Install pip and re-run.")
        sys.exit(1)
    ok("pip found")


def install_deps() -> None:
    step(2, TOTAL_STEPS, "Installing dependencies")
    req = ROOT / "requirements.txt"
    if not req.exists():
        warn("requirements.txt not found — skipping.")
        return
    print(c(DIM, f"\n  Running: pip install -r requirements.txt\n"))
    try:
        run([sys.executable, "-m", "pip", "install", "-r", str(req), "--quiet"])
        ok("All dependencies installed")
    except subprocess.CalledProcessError:
        err("pip install failed. Fix the errors above and re-run.")
        sys.exit(1)


def configure_env() -> None:
    step(3, TOTAL_STEPS, "Configuring environment")

    env_path = ROOT / ".env"
    if env_path.exists():
        warn(".env already exists.")
        if not ask_yn("Overwrite it?", default=False):
            ok("Keeping existing .env")
            return

    provider = ask_choice(
        "Which LLM provider will you use?",
        [
            ("anthropic", "Anthropic  (Claude — recommended)"),
            ("openai",    "OpenAI     (GPT-4o / GPT-4.1)"),
            ("azure",     "Azure OpenAI"),
        ],
    )

    lines: list[str] = [
        "# Generated by install.py — edit anytime\n",
        f"CHIKA_PROVIDER={provider}\n",
        "\n",
    ]

    if provider == "anthropic":
        print()
        info("Get your key at: console.anthropic.com → API Keys")
        key = ask_secret("Anthropic API key (sk-ant-…)")
        model = ask("Model", default="claude-sonnet-4-6")
        lines += [
            f"ANTHROPIC_API_KEY={key}\n",
            f"ANTHROPIC_MODEL={model}\n",
        ]

    elif provider == "openai":
        print()
        info("Get your key at: platform.openai.com → API Keys")
        key = ask_secret("OpenAI API key (sk-…)")
        model = ask("Model", default="gpt-4o")
        lines += [
            f"OPENAI_API_KEY={key}\n",
            f"OPENAI_MODEL={model}\n",
        ]

    elif provider == "azure":
        print()
        key      = ask_secret("Azure OpenAI API key")
        endpoint = ask("Azure endpoint (https://…openai.azure.com/)")
        deploy   = ask("Deployment name", default="gpt-4o")
        lines += [
            f"AZURE_OPENAI_ENDPOINT={endpoint}\n",
            f"AZURE_OPENAI_KEY={key}\n",
            f"AZURE_OPENAI_DEPLOYMENT={deploy}\n",
            "AZURE_API_VERSION=2024-10-21\n",
        ]

    lines += [
        "\n# Engine settings\n",
        "CHIKA_MAX_HISTORY_TOKENS=10000\n",
        "CHIKA_MAX_WORKFLOW_STEPS=8\n",
        "CHIKA_MAX_TOOL_TURNS=20\n",
        "CHIKA_THINKING=true\n",
        "CHIKA_VALIDATE_RESPONSE=true\n",
        "CHIKA_HOST=0.0.0.0\n",
        "CHIKA_PORT=8000\n",
        "CHIKA_API_KEY=\n",
    ]

    env_path.write_text("".join(lines), encoding="utf-8")
    ok(f".env written → {env_path}")


def verify_setup() -> None:
    step(4, TOTAL_STEPS, "Verifying setup")
    try:
        result = run(
            [sys.executable, "-c", "from api.session_manager import session_manager; print('ok')"],
            capture=True,
        )
        if "ok" in result.stdout:
            ok("Core imports working")
        else:
            raise RuntimeError("unexpected output")
    except Exception as e:
        err(f"Import check failed: {e}")
        warn("Try running manually: python api/server.py")


def print_extension_instructions() -> None:
    step(5, TOTAL_STEPS, "Extension setup")
    ext_path = (ROOT / "extension").resolve()
    print()
    print(c(BOLD, "  Load the Chrome extension (one-time, takes 60 seconds):"))
    print()
    steps = [
        ("Open Chrome and go to",         c(CYAN + BOLD, "chrome://extensions")),
        ("Enable",                          c(BOLD, "Developer mode") + c(DIM, "  (toggle, top-right corner)")),
        ("Click",                           c(BOLD, "Load unpacked")),
        ("Select this folder:",             c(CYAN, str(ext_path))),
        ("Click the",                       c(BOLD, "Chika") + " icon in your toolbar → " + c(BOLD, "Options")),
        ("Server URL should be",            c(CYAN + BOLD, "http://localhost:8000") + c(DIM, "  (already set)")),
        ("Click",                           c(BOLD, "Test connection") + c(DIM, "  — should show ") + c(GREEN, "Connected!")),
    ]
    for i, (label, value) in enumerate(steps, 1):
        print(f"    {c(BOLD+CYAN, str(i)+'.')}  {label} {value}")
    print()

    print(c(DIM, "  ─────────────────────────────────────────────────"))
    print()
    print(c(BOLD, "  Firefox / Edge?"))
    print(c(DIM,  "  Edge:    edge://extensions → same steps as Chrome"))
    print(c(DIM,  "  Firefox: about:debugging → This Firefox → Load Temporary Add-on"))
    print(c(DIM,  "           → select extension/manifest.json"))
    print()


def print_start_instructions(start_now: bool) -> None:
    rule()
    print()
    print(c(BOLD + GREEN, "  Chika is ready!"))
    print()
    if not start_now:
        print(c(BOLD, "  Start the server:"))
        print()
        if sys.platform == "win32":
            print(c(CYAN, "    .\\start.ps1"))
            print(c(DIM,  "    — or —"))
            print(c(CYAN, "    python api/server.py"))
        else:
            print(c(CYAN, "    python api/server.py"))
        print()

    print(c(BOLD, "  Then open:"))
    print()
    print(c(CYAN + BOLD, "    http://localhost:8000"))
    print()
    print(c(DIM,  "  CLI mode (no browser needed):"))
    print(c(CYAN, "    python chika.py"))
    print()
    rule()
    print()


def start_server() -> None:
    server = ROOT / "api" / "server.py"
    if not server.exists():
        err("api/server.py not found")
        return
    print()
    info("Starting server on http://localhost:8000  (Ctrl+C to stop)")
    print()
    try:
        os.execv(sys.executable, [sys.executable, str(server)])
    except Exception as e:
        err(f"Could not start server: {e}")
        warn(f"Run manually: python {server}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    # Windows: enable ANSI codes
    if sys.platform == "win32":
        os.system("color")

    banner()

    check_python()
    install_deps()
    configure_env()
    verify_setup()
    print_extension_instructions()

    start_now = ask_yn("Start Chika server now?", default=True)
    print_start_instructions(start_now)

    if start_now:
        start_server()


if __name__ == "__main__":
    main()
