// AUTO-GENERATED by scripts/gen_openapi_client.py — DO NOT EDIT.
// Source of truth: api/server.py (FastAPI route definitions).
// Regenerate: python scripts/gen_openapi_client.py
// CI guard:   python scripts/gen_openapi_client.py --check
// Generated:  2026-05-06

// ── Schema interfaces ────────────────────────────────────────

/** OpenAPI schema: EnvUpdate. */
export interface EnvUpdate {
  set?: Record<string, string> | null;
  unset?: string[] | null;
}

/** OpenAPI schema: HTTPValidationError. */
export interface HTTPValidationError {
  detail?: ValidationError[];
}

/** OpenAPI schema: PetUpdate. */
export interface PetUpdate {
  pet_id: string | null;
  memory_action?: string | null;
}

/** OpenAPI schema: ProviderUpdate. */
export interface ProviderUpdate {
  provider?: string | null;
  model?: string | null;
}

/** OpenAPI schema: SettingsPatch. */
export interface SettingsPatch {
  autonomy?: string | null;
  tool_permissions?: Record<string, string> | null;
  pet_speech?: string | null;
  pet_speech_tokens?: number | null;
  auto_continue?: string | null;
  auto_continue_max?: number | null;
}

/** OpenAPI schema: ValidationError. */
export interface ValidationError {
  loc: string | number[];
  msg: string;
  type: string;
  input?: any;
  ctx?: Record<string, any>;
}

/** OpenAPI schema: _AuthenticateProfile. */
export interface _AuthenticateProfile {
  name: string;
  password?: string;
}

/** OpenAPI schema: _CreateProfile. */
export interface _CreateProfile {
  name: string;
  password?: string | null;
}

/** OpenAPI schema: _SelectProfile. */
export interface _SelectProfile {
  session_id: string;
  name: string;
  password?: string;
}

/** OpenAPI schema: _SetPassword. */
export interface _SetPassword {
  old_password?: string;
  new_password?: string;
}
