// AUTO-GENERATED by scripts/gen_event_types.py — DO NOT EDIT BY HAND.
// Source of truth: api/models.py (Pydantic event models).
// Regenerate: python scripts/gen_event_types.py
// CI guard:   python scripts/gen_event_types.py --check
// Generated:  2026-05-06

/** Every engine event type the WebSocket may emit. */
export type EventTypeName =
  | "token"
  | "thinking"
  | "thinking_end"
  | "workflow_start"
  | "workflow_done"
  | "step_start"
  | "step_done"
  | "loop_iteration"
  | "condition_eval"
  | "map_item"
  | "retry_attempt"
  | "retry_backoff"
  | "retry_notice"
  | "tool_call"
  | "tool_result"
  | "variable_set"
  | "memory_update"
  | "compaction"
  | "validation_warning"
  | "done"
  | "error"
  | "cancelled"
  | "chat_title"
  | "chat_list"
  | "session_info"
  | "profile_info"
  | "profile_switch_done"
  | "settings_info"
  | "pet_changed"
  | "extension_status"
  | "reset_done"
  | "approval_required"
  | "shell_process_start"
  | "shell_output"
  | "shell_process_done"
  | "ext_chat_start"
  | "ext_chat_turn"
  | "ext_chat_error"
  | "ext_chat_done"
  | "ping"
  | "pong";

/** Engine event: ``CompactionEvent``. */
export interface CompactionEvent {
  type?: string;
  removed: number;
  kept: number;
  summary_preview?: string;
}

/** Engine event: ``ConditionEvalEvent``. */
export interface ConditionEvalEvent {
  type?: string;
  step_id: string;
  condition: any;
  result: boolean;
}

/** Engine event: ``DoneEvent``. */
export interface DoneEvent {
  type?: string;
}

/** Engine event: ``ErrorEvent``. */
export interface ErrorEvent {
  type?: string;
  message: string;
  step_id?: string | null;
}

/** Engine event: ``LoopIterationEvent``. */
export interface LoopIterationEvent {
  type?: string;
  step_id: string;
  iteration: number;
  max: number;
}

/** Engine event: ``MapItemEvent``. */
export interface MapItemEvent {
  type?: string;
  step_id: string;
  index: number;
  total: number;
}

/** Engine event: ``MemoryUpdateEvent``. */
export interface MemoryUpdateEvent {
  type?: string;
  key: string;
  value: string;
}

/** Engine event: ``RetryAttemptEvent``. */
export interface RetryAttemptEvent {
  type?: string;
  step_id: string;
  attempt: number;
  max: number;
}

/** Engine event: ``StepDoneEvent``. */
export interface StepDoneEvent {
  type?: string;
  step_id: string;
  duration_ms: number;
}

/** Engine event: ``StepStartEvent``. */
export interface StepStartEvent {
  type?: string;
  step_id: string;
  step_type: string;
  workflow_id?: string | null;
}

/** Engine event: ``TokenEvent``. */
export interface TokenEvent {
  type?: string;
  text: string;
}

/** Engine event: ``ToolCallEvent``. */
export interface ToolCallEvent {
  type?: string;
  step_id: string;
  tool: string;
  args: Record<string, any>;
}

/** Engine event: ``ToolResultEvent``. */
export interface ToolResultEvent {
  type?: string;
  step_id: string;
  tool: string;
  result: any;
  error?: string | null;
  duration_ms: number;
}

/** Engine event: ``VariableSetEvent``. */
export interface VariableSetEvent {
  type?: string;
  name: string;
  var_type: string;
  size_bytes: number;
  value_preview?: string;
}

/** Engine event: ``WorkflowDoneEvent``. */
export interface WorkflowDoneEvent {
  type?: string;
  workflow_id: string;
  variables: Record<string, any>;
}

/** Engine event: ``WorkflowStartEvent``. */
export interface WorkflowStartEvent {
  type?: string;
  workflow_id: string;
  name: string;
}

/** Discriminated union of every engine event. */
export type EngineEvent = CompactionEvent | ConditionEvalEvent | DoneEvent | ErrorEvent | LoopIterationEvent | MapItemEvent | MemoryUpdateEvent | RetryAttemptEvent | StepDoneEvent | StepStartEvent | TokenEvent | ToolCallEvent | ToolResultEvent | VariableSetEvent | WorkflowDoneEvent | WorkflowStartEvent;

