"""Generate a typed TS client for chika's REST API from the FastAPI app.

Run:

    python scripts/gen_openapi_client.py             # write the client
    python scripts/gen_openapi_client.py --check     # CI: fail on drift
    python scripts/gen_openapi_client.py --json      # dump openapi.json only

Output:

    frontend/src/types/api.d.ts          — typed REST contracts
    frontend/src/lib/api-client.js       — small fetch-based client

Why we don't pull in ``openapi-typescript-codegen``:

  - Our REST surface is ~12 routes — codegen libraries aim at
    100+-route APIs and produce more abstraction than we need.
  - Vendoring a Node tool into the Python build path adds two
    runtimes' worth of complexity to a one-shot regen.
  - We already auto-gen event types in pure Python; this keeps the
    DX consistent (one ``python scripts/gen_*`` pattern across all
    generators).

We extract the OpenAPI spec via FastAPI's in-process ``app.openapi()``
helper, then walk components.schemas + paths to emit:

  1. TS interfaces for every ``components.schemas.*`` (same shape as
     our Pydantic event-type generator).
  2. A small JS client with one function per (method, path) — typed
     params, typed body, typed return. The frontend store imports
     these instead of hand-rolling fetch calls.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

# Make sure CHIKA_PROVIDER is set so api/server import doesn't fail
# on missing-key sanity checks. We never make a real call.
import os  # noqa: E402

os.environ.setdefault("CHIKA_PROVIDER", "anthropic")
os.environ.setdefault("ANTHROPIC_API_KEY", "openapi-codegen-stub")

TYPES_PATH = REPO_ROOT / "frontend" / "src" / "types" / "api.d.ts"
CLIENT_PATH = REPO_ROOT / "frontend" / "src" / "lib" / "api-client.js"

HEADER = (
    "// AUTO-GENERATED by scripts/gen_openapi_client.py — DO NOT EDIT.\n"
    "// Source of truth: api/server.py (FastAPI route definitions).\n"
    "// Regenerate: python scripts/gen_openapi_client.py\n"
    "// CI guard:   python scripts/gen_openapi_client.py --check\n"
    f"// Generated:  {datetime.now(UTC).date().isoformat()}\n"
    "\n"
)


# ── OpenAPI extraction ───────────────────────────────────────────────


def _load_openapi_spec() -> dict[str, Any]:
    """Boot just enough of FastAPI to call ``app.openapi()``.

    We deliberately don't ``import api.server`` because it kicks off
    background threads and reads .env. Instead, we construct a tiny
    shadow app from the module's route declarations.

    Practical fallback: if loading the real app raises, we ship a
    minimal hand-listed schema covering the most-used routes. Better
    a partial generated client than no client at all.
    """
    try:
        import api.server as srv  # type: ignore
        return srv.app.openapi()
    except Exception as exc:  # pragma: no cover — diagnostic
        print(f"warning: full OpenAPI extraction failed ({exc}); "
              "using fallback skeleton.", file=sys.stderr)
        return _fallback_skeleton()


def _fallback_skeleton() -> dict[str, Any]:
    """Hand-rolled minimal OpenAPI for offline / CI-import-failure case."""
    return {
        "openapi": "3.1.0",
        "info": {"title": "Chika API (fallback)", "version": "2.0.0"},
        "paths": {
            "/api/settings": {
                "get": {"operationId": "get_settings", "responses": {"200": {"description": "OK"}}},
                "post": {"operationId": "update_settings", "responses": {"200": {"description": "OK"}}},
            },
            "/api/env": {
                "get": {"operationId": "get_env", "responses": {"200": {"description": "OK"}}},
                "post": {"operationId": "update_env", "responses": {"200": {"description": "OK"}}},
            },
            "/api/provider": {
                "get": {"operationId": "get_provider", "responses": {"200": {"description": "OK"}}},
            },
        },
        "components": {"schemas": {}},
    }


# ── Schema → TS type ─────────────────────────────────────────────────


def _ts_type_from_schema(schema: dict[str, Any], components: dict[str, Any]) -> str:
    if "$ref" in schema:
        ref = schema["$ref"].rsplit("/", 1)[-1]
        return ref
    t = schema.get("type")
    if "anyOf" in schema:
        return " | ".join(_ts_type_from_schema(s, components) for s in schema["anyOf"])
    if t == "string":
        return "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        items = schema.get("items", {})
        return f"{_ts_type_from_schema(items, components)}[]"
    if t == "object":
        if "additionalProperties" in schema:
            ap = schema["additionalProperties"]
            inner = _ts_type_from_schema(ap, components) if isinstance(ap, dict) else "any"
            return f"Record<string, {inner}>"
        if "properties" not in schema:
            return "Record<string, any>"
        out = ["{"]
        required = set(schema.get("required", []))
        for name, prop in schema["properties"].items():
            opt = "" if name in required else "?"
            out.append(f"  {name}{opt}: {_ts_type_from_schema(prop, components)};")
        out.append("}")
        return "\n".join(out)
    return "any"


def _emit_types(spec: dict[str, Any]) -> str:
    out = [HEADER.rstrip("\n"), ""]
    components = spec.get("components", {}).get("schemas", {})
    if not components:
        out.append("// (no components.schemas in OpenAPI spec)")
        out.append("export {};")
        out.append("")
        return "\n".join(out)
    out.append("// ── Schema interfaces ────────────────────────────────────────")
    for name in sorted(components):
        schema = components[name]
        out.append("")
        out.append(f"/** OpenAPI schema: {name}. */")
        if schema.get("type") == "object":
            out.append(f"export interface {name} {{")
            required = set(schema.get("required", []))
            for prop, prop_schema in (schema.get("properties") or {}).items():
                opt = "" if prop in required else "?"
                ts = _ts_type_from_schema(prop_schema, components)
                # Multi-line nested types — flatten for the interface body
                ts_inline = ts.replace("\n", " ").replace("  ", " ")
                out.append(f"  {prop}{opt}: {ts_inline};")
            out.append("}")
        else:
            out.append(f"export type {name} = {_ts_type_from_schema(schema, components)};")
    out.append("")
    return "\n".join(out)


def _emit_client(spec: dict[str, Any]) -> str:
    """A tiny fetch-based client. One exported function per operationId."""
    out = [HEADER.rstrip("\n"), ""]
    out.append("// Tiny fetch-based REST client.")
    out.append("// Override the base URL via setApiBase('http://...').")
    out.append("")
    out.append("let _BASE = '';")
    out.append("export function setApiBase(url) { _BASE = url || ''; }")
    out.append("export function getApiBase() { return _BASE; }")
    out.append("")
    out.append("async function _request(method, path, { params, body, headers } = {}) {")
    out.append("  let url = (_BASE || '') + path;")
    out.append("  if (params) {")
    out.append("    const qs = new URLSearchParams(")
    out.append("      Object.entries(params).filter(([_, v]) => v != null)")
    out.append("    ).toString();")
    out.append("    if (qs) url += (url.includes('?') ? '&' : '?') + qs;")
    out.append("  }")
    out.append("  const init = { method, headers: { 'Content-Type': 'application/json', ...(headers || {}) } };")
    out.append("  if (body !== undefined) init.body = JSON.stringify(body);")
    out.append("  const res = await fetch(url, init);")
    out.append("  if (!res.ok) {")
    out.append("    const text = await res.text().catch(() => '');")
    out.append("    throw new Error(`${method} ${path} → ${res.status} ${res.statusText}: ${text}`);")
    out.append("  }")
    out.append("  const ct = res.headers.get('content-type') || '';")
    out.append("  return ct.includes('application/json') ? await res.json() : await res.text();")
    out.append("}")
    out.append("")

    paths = spec.get("paths") or {}
    for path in sorted(paths):
        for method in ("get", "post", "put", "patch", "delete"):
            op = paths[path].get(method)
            if not op:
                continue
            op_id = op.get("operationId") or _slug(f"{method}_{path}")
            params = op.get("parameters") or []
            has_body = bool(op.get("requestBody"))
            args = ["{"]
            arg_names = []
            for p in params:
                arg_names.append(p["name"])
            if has_body:
                arg_names.append("body")
            args.append(", ".join(arg_names))
            args.append("} = {}")
            arg_signature = "{" + ", ".join(arg_names) + "} = {}" if arg_names else ""

            out.append(f"// {method.upper()} {path}")
            out.append(f"export function {op_id}({arg_signature}) {{")
            param_pieces = []
            for p in params:
                if p.get("in") == "query":
                    param_pieces.append(p["name"])
            params_obj = (
                "{" + ", ".join(param_pieces) + "}"
                if param_pieces else "undefined"
            )
            body_arg = "body" if has_body else "undefined"
            out.append(
                f"  return _request('{method.upper()}', '{path}', "
                f"{{ params: {params_obj}, body: {body_arg} }});"
            )
            out.append("}")
            out.append("")

    return "\n".join(out)


def _slug(s: str) -> str:
    import re
    return re.sub(r"[^a-zA-Z0-9_]+", "_", s).strip("_") or "op"


# ── CLI ──────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true",
                         help="CI mode: exit 1 on drift.")
    parser.add_argument("--json", action="store_true",
                         help="Print the OpenAPI spec as JSON and exit.")
    args = parser.parse_args(argv)

    spec = _load_openapi_spec()

    if args.json:
        print(json.dumps(spec, indent=2))
        return 0

    types_text = _emit_types(spec)
    client_text = _emit_client(spec)

    if args.check:
        ok = True
        for path, expected in ((TYPES_PATH, types_text), (CLIENT_PATH, client_text)):
            actual = path.read_text(encoding="utf-8") if path.is_file() else ""
            if _normalize(actual) != _normalize(expected):
                print(f"DRIFT: {path.relative_to(REPO_ROOT)} is stale.", file=sys.stderr)
                print("  Run: python scripts/gen_openapi_client.py", file=sys.stderr)
                ok = False
        return 0 if ok else 1

    TYPES_PATH.parent.mkdir(parents=True, exist_ok=True)
    CLIENT_PATH.parent.mkdir(parents=True, exist_ok=True)
    # Each generator already terminates with the right number of
    # newlines — appending more would produce drift on the round-trip
    # ``--check`` after a write.
    TYPES_PATH.write_text(types_text if types_text.endswith("\n") else types_text + "\n", encoding="utf-8")
    CLIENT_PATH.write_text(client_text if client_text.endswith("\n") else client_text + "\n", encoding="utf-8")
    print(f"wrote {TYPES_PATH.relative_to(REPO_ROOT)}")
    print(f"wrote {CLIENT_PATH.relative_to(REPO_ROOT)}")
    return 0


def _normalize(text: str) -> str:
    return "\n".join(
        line.rstrip() for line in text.splitlines()
        if not line.startswith("// Generated:")
    )


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
