"""Generate TS + JSDoc types for engine events from ``api/models.py``.

Run:

    python scripts/gen_event_types.py             # write the files
    python scripts/gen_event_types.py --check     # CI mode: fail if stale

Outputs:

    frontend/src/types/events.d.ts
    extension/lib/event-types.js

Why this script exists
----------------------
The audit (ADR-31) found that the frontend's Vue store typings and
the extension's JSDoc were hand-maintained against the engine's
event payloads. Whenever ``api/models.py`` changed, somebody had to
remember to update both — and they didn't. Drift was invisible until
runtime.

Generating from the Pydantic models means:

  - The Pydantic models are the single source of truth.
  - ``--check`` mode in CI fails when the generated files don't match
    what the current ``api/models.py`` would produce. Drift is a
    pull-request-blocker, not a runtime surprise.
  - Adding a new event type is a one-step operation.

Type mapping
------------
We hand-roll a small mapper rather than pulling in
``datamodel-code-generator``. The reason: our Pydantic surface is
tiny (~16 event models) and locked-down (audited types only). A 200-
line generator we own beats a 20 MB dep we don't.

Mapping table:

  str             → string
  int / float     → number
  bool            → boolean
  None / Any      → any  (TS) / *  (JSDoc)
  list[X]         → X[]
  dict[str, X]    → Record<string, X>
  X | Y           → X | Y
  Optional[X]     → X | null

Pydantic Field defaults are honoured: a field with a default is
optional in the generated TS (``foo?: string``).
"""
from __future__ import annotations

import argparse
import sys
import types
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, get_args, get_origin

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from pydantic import BaseModel  # noqa: E402

from api import models as api_models  # noqa: E402

TS_PATH = REPO_ROOT / "frontend" / "src" / "types" / "events.d.ts"
JSDOC_PATH = REPO_ROOT / "extension" / "lib" / "event-types.js"

HEADER_BANNER = (
    "// AUTO-GENERATED by scripts/gen_event_types.py — DO NOT EDIT BY HAND.\n"
    "// Source of truth: api/models.py (Pydantic event models).\n"
    "// Regenerate: python scripts/gen_event_types.py\n"
    "// CI guard:   python scripts/gen_event_types.py --check\n"
    f"// Generated:  {datetime.now(UTC).date().isoformat()}\n"
    "\n"
)


# ── Type mapping ─────────────────────────────────────────────────────


def _ts_type(annotation: Any) -> str:
    """Map a Python type annotation to a TS type string."""
    if annotation is type(None):
        return "null"
    if annotation is str:
        return "string"
    if annotation is int or annotation is float:
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is Any or annotation is None:
        return "any"

    origin = get_origin(annotation)
    args = get_args(annotation)

    # X | Y (PEP 604) and Union[X, Y]
    if origin is types.UnionType or (origin is not None and origin.__name__ == "Union"):
        return " | ".join(_ts_type(a) for a in args)

    if origin in (list, list[Any].__class__):  # noqa: SIM118 - origin equality is fine
        return f"{_ts_type(args[0])}[]" if args else "any[]"
    if origin is list:
        return f"{_ts_type(args[0])}[]" if args else "any[]"
    if origin is tuple:
        if not args:
            return "any[]"
        return "[" + ", ".join(_ts_type(a) for a in args) + "]"
    if origin is dict:
        if not args:
            return "Record<string, any>"
        k_t = _ts_type(args[0])
        v_t = _ts_type(args[1])
        return f"Record<{k_t}, {v_t}>"

    # Fallback: anything else gets "any" — no hidden surprises
    name = getattr(annotation, "__name__", None)
    if name in ("str", "int", "float", "bool"):
        return _ts_type({"str": str, "int": int, "float": float, "bool": bool}[name])
    return "any"


def _jsdoc_type(annotation: Any) -> str:
    """JSDoc variant of ``_ts_type``. Slightly different syntax."""
    ts = _ts_type(annotation)
    # JSDoc uses ``*`` for any.
    return ts.replace("any", "*").replace("string", "string").replace("number", "number")


# ── Model walking ────────────────────────────────────────────────────


def _is_optional(field) -> bool:
    """A field is optional in TS if it has a default OR its annotation
    is a Union including None."""
    if field.default is not None and field.default.__class__.__name__ != "PydanticUndefinedType":
        # Has a literal default
        return True
    annotation = field.annotation
    origin = get_origin(annotation)
    if origin is types.UnionType or (origin is not None and origin.__name__ == "Union"):
        return type(None) in get_args(annotation)
    return False


def _model_fields(model: type[BaseModel]) -> list[tuple[str, Any, bool]]:
    """Return ``[(name, annotation, is_optional)]`` for the model."""
    out = []
    for name, info in model.model_fields.items():
        out.append((name, info.annotation, _is_optional(info)))
    return out


def _event_models() -> list[type[BaseModel]]:
    """Discover every event-shaped Pydantic model in api.models.

    Heuristic: it's a BaseModel subclass with a ``type`` field whose
    default matches one of the EventType enum values. Skips
    ``UserMessage`` (inbound) and ``SettingsPatch`` (REST body).
    """
    valid_event_values = {et.value for et in api_models.EventType}
    out = []
    for name in dir(api_models):
        obj = getattr(api_models, name)
        if not isinstance(obj, type) or not issubclass(obj, BaseModel) or obj is BaseModel:
            continue
        type_field = obj.model_fields.get("type")
        if type_field is None:
            continue
        default = type_field.default
        if isinstance(default, str) and default in valid_event_values:
            out.append(obj)
    return sorted(out, key=lambda m: m.__name__)


# ── Generators ───────────────────────────────────────────────────────


def generate_ts() -> str:
    lines = [HEADER_BANNER.rstrip("\n")]
    lines.append("")
    lines.append("/** Every engine event type the WebSocket may emit. */")
    lines.append("export type EventTypeName =")
    enum_values = [et.value for et in api_models.EventType]
    for i, v in enumerate(enum_values):
        suffix = ";" if i == len(enum_values) - 1 else ""
        lines.append(f'  | "{v}"{suffix}')
    lines.append("")

    for model in _event_models():
        lines.append(f"/** Engine event: ``{model.__name__}``. */")
        lines.append(f"export interface {model.__name__} {{")
        for name, ann, optional in _model_fields(model):
            ts = _ts_type(ann)
            opt = "?" if optional else ""
            lines.append(f"  {name}{opt}: {ts};")
        lines.append("}")
        lines.append("")

    # Union of all event interfaces.
    lines.append("/** Discriminated union of every engine event. */")
    union = " | ".join(m.__name__ for m in _event_models())
    lines.append(f"export type EngineEvent = {union or 'unknown'};")
    lines.append("")

    return "\n".join(lines) + "\n"


def generate_jsdoc() -> str:
    lines = [HEADER_BANNER.rstrip("\n")]
    lines.append("")
    lines.append("// JSDoc @typedef block consumed by the extension's")
    lines.append("// vanilla-JS source. Use as:  /** @type {import('./event-types').TokenEvent} */")
    lines.append("")

    enum_values = [et.value for et in api_models.EventType]
    lines.append("/**")
    lines.append(" * @typedef {(")
    for i, v in enumerate(enum_values):
        sep = "" if i == len(enum_values) - 1 else " |"
        lines.append(f' *   "{v}"{sep}')
    lines.append(" * )} EventTypeName")
    lines.append(" */")
    lines.append("")

    for model in _event_models():
        lines.append("/**")
        lines.append(f" * @typedef {{Object}} {model.__name__}")
        for name, ann, optional in _model_fields(model):
            jt = _jsdoc_type(ann)
            opt = " [optional]" if optional else ""
            lines.append(f" * @property {{{jt}}} {name}{opt}")
        lines.append(" */")
        lines.append("")

    lines.append("/**")
    union = " | ".join(m.__name__ for m in _event_models())
    lines.append(f" * @typedef {{({union or 'never'})}} EngineEvent")
    lines.append(" */")
    lines.append("")
    lines.append("// Module marker so this file can be imported as a side-effect")
    lines.append("// from typed JSDoc consumers without complaints.")
    lines.append("export {};")
    lines.append("")
    return "\n".join(lines)


# ── CLI ──────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--check", action="store_true",
        help="CI mode: exit 1 if generated files don't match what we would generate.",
    )
    args = parser.parse_args(argv)

    ts_content = generate_ts()
    js_content = generate_jsdoc()

    if args.check:
        ok = True
        for path, expected in ((TS_PATH, ts_content), (JSDOC_PATH, js_content)):
            actual = path.read_text(encoding="utf-8") if path.is_file() else ""
            if _normalize(actual) != _normalize(expected):
                print(f"DRIFT: {path.relative_to(REPO_ROOT)} is stale.", file=sys.stderr)
                print("  Run: python scripts/gen_event_types.py", file=sys.stderr)
                ok = False
        return 0 if ok else 1

    TS_PATH.parent.mkdir(parents=True, exist_ok=True)
    JSDOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    TS_PATH.write_text(ts_content, encoding="utf-8")
    JSDOC_PATH.write_text(js_content, encoding="utf-8")
    print(f"wrote {TS_PATH.relative_to(REPO_ROOT)}")
    print(f"wrote {JSDOC_PATH.relative_to(REPO_ROOT)}")
    return 0


def _normalize(text: str) -> str:
    """Compare ignoring the auto-generated date stamp + trailing whitespace."""
    return "\n".join(
        line.rstrip() for line in text.splitlines()
        if not line.startswith("// Generated:")
    )


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
