// AUTO-GENERATED by scripts/gen_openapi_client.py — DO NOT EDIT.
// Source of truth: api/server.py (FastAPI route definitions).
// Regenerate: python scripts/gen_openapi_client.py
// CI guard:   python scripts/gen_openapi_client.py --check
// Generated:  2026-05-06

// Tiny fetch-based REST client.
// Override the base URL via setApiBase('http://...').

let _BASE = '';
export function setApiBase(url) { _BASE = url || ''; }
export function getApiBase() { return _BASE; }

async function _request(method, path, { params, body, headers } = {}) {
  let url = (_BASE || '') + path;
  if (params) {
    const qs = new URLSearchParams(
      Object.entries(params).filter(([_, v]) => v != null)
    ).toString();
    if (qs) url += (url.includes('?') ? '&' : '?') + qs;
  }
  const init = { method, headers: { 'Content-Type': 'application/json', ...(headers || {}) } };
  if (body !== undefined) init.body = JSON.stringify(body);
  const res = await fetch(url, init);
  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(`${method} ${path} → ${res.status} ${res.statusText}: ${text}`);
  }
  const ct = res.headers.get('content-type') || '';
  return ct.includes('application/json') ? await res.json() : await res.text();
}

// GET /api/config
export function get_public_config_api_config_get({authorization} = {}) {
  return _request('GET', '/api/config', { params: undefined, body: undefined });
}

// GET /api/env
export function get_env_api_env_get({show_secrets, authorization} = {}) {
  return _request('GET', '/api/env', { params: {show_secrets}, body: undefined });
}

// PATCH /api/env
export function patch_env_api_env_patch({authorization, body} = {}) {
  return _request('PATCH', '/api/env', { params: undefined, body: body });
}

// GET /api/extension/status
export function extension_status_api_extension_status_get({authorization} = {}) {
  return _request('GET', '/api/extension/status', { params: undefined, body: undefined });
}

// GET /api/pets
export function list_pets_api_pets_get({authorization} = {}) {
  return _request('GET', '/api/pets', { params: undefined, body: undefined });
}

// GET /api/profile/{name}/pet
export function get_profile_pet_api_profile__name__pet_get({name, authorization} = {}) {
  return _request('GET', '/api/profile/{name}/pet', { params: undefined, body: undefined });
}

// PATCH /api/profile/{name}/pet
export function set_profile_pet_api_profile__name__pet_patch({name, authorization, body} = {}) {
  return _request('PATCH', '/api/profile/{name}/pet', { params: undefined, body: body });
}

// GET /api/profile/{profile_name}/chats
export function list_profile_chats_api_profile__profile_name__chats_get({profile_name, authorization} = {}) {
  return _request('GET', '/api/profile/{profile_name}/chats', { params: undefined, body: undefined });
}

// DELETE /api/profile/{profile_name}/chats/{chat_id}
export function delete_profile_chat_api_profile__profile_name__chats__chat_id__delete({profile_name, chat_id, authorization} = {}) {
  return _request('DELETE', '/api/profile/{profile_name}/chats/{chat_id}', { params: undefined, body: undefined });
}

// GET /api/profiles
export function list_profiles_api_profiles_get({authorization} = {}) {
  return _request('GET', '/api/profiles', { params: undefined, body: undefined });
}

// POST /api/profiles/authenticate
export function authenticate_profile_api_profiles_authenticate_post({authorization, body} = {}) {
  return _request('POST', '/api/profiles/authenticate', { params: undefined, body: body });
}

// POST /api/profiles/create
export function create_profile_api_profiles_create_post({authorization, body} = {}) {
  return _request('POST', '/api/profiles/create', { params: undefined, body: body });
}

// POST /api/profiles/select
export function select_profile_api_profiles_select_post({authorization, body} = {}) {
  return _request('POST', '/api/profiles/select', { params: undefined, body: body });
}

// POST /api/profiles/{name}/password
export function set_profile_password_api_profiles__name__password_post({name, authorization, body} = {}) {
  return _request('POST', '/api/profiles/{name}/password', { params: undefined, body: body });
}

// GET /api/provider
export function get_provider_api_provider_get({authorization} = {}) {
  return _request('GET', '/api/provider', { params: undefined, body: undefined });
}

// PATCH /api/provider
export function patch_provider_api_provider_patch({authorization, body} = {}) {
  return _request('PATCH', '/api/provider', { params: undefined, body: body });
}

// DELETE /api/session/{session_id}
export function delete_session_api_session__session_id__delete({session_id, authorization} = {}) {
  return _request('DELETE', '/api/session/{session_id}', { params: undefined, body: undefined });
}

// GET /api/session/{session_id}/history
export function get_history_api_session__session_id__history_get({session_id, authorization} = {}) {
  return _request('GET', '/api/session/{session_id}/history', { params: undefined, body: undefined });
}

// GET /api/session/{session_id}/memory
export function get_memory_api_session__session_id__memory_get({session_id, authorization} = {}) {
  return _request('GET', '/api/session/{session_id}/memory', { params: undefined, body: undefined });
}

// POST /api/session/{session_id}/reset
export function reset_session_api_session__session_id__reset_post({session_id, authorization} = {}) {
  return _request('POST', '/api/session/{session_id}/reset', { params: undefined, body: undefined });
}

// GET /api/session/{session_id}/variables
export function get_variables_api_session__session_id__variables_get({session_id, authorization} = {}) {
  return _request('GET', '/api/session/{session_id}/variables', { params: undefined, body: undefined });
}

// GET /api/sessions
export function list_sessions_api_sessions_get({authorization} = {}) {
  return _request('GET', '/api/sessions', { params: undefined, body: undefined });
}

// GET /api/settings
export function get_settings_api_settings_get({authorization} = {}) {
  return _request('GET', '/api/settings', { params: undefined, body: undefined });
}

// PATCH /api/settings
export function patch_settings_api_settings_patch({authorization, body} = {}) {
  return _request('PATCH', '/api/settings', { params: undefined, body: body });
}

// GET /api/shells
export function list_shells_api_shells_get({authorization} = {}) {
  return _request('GET', '/api/shells', { params: undefined, body: undefined });
}

// POST /api/shells/kill_all
export function kill_all_shells_api_shells_kill_all_post({authorization} = {}) {
  return _request('POST', '/api/shells/kill_all', { params: undefined, body: undefined });
}

// POST /api/shells/{pid}/kill
export function kill_shell_api_shells__pid__kill_post({pid, authorization} = {}) {
  return _request('POST', '/api/shells/{pid}/kill', { params: undefined, body: undefined });
}

// GET /api/skills
export function get_skills_api_skills_get({authorization} = {}) {
  return _request('GET', '/api/skills', { params: undefined, body: undefined });
}

// GET /api/tools
export function get_tools_api_tools_get({authorization} = {}) {
  return _request('GET', '/api/tools', { params: undefined, body: undefined });
}

// GET /api/workflows
export function get_workflows_api_workflows_get({authorization} = {}) {
  return _request('GET', '/api/workflows', { params: undefined, body: undefined });
}

// GET /auth/spotify
export function spotify_auth_start_auth_spotify_get() {
  return _request('GET', '/auth/spotify', { params: undefined, body: undefined });
}

// GET /auth/spotify/callback
export function spotify_auth_callback_auth_spotify_callback_get({code, state, error} = {}) {
  return _request('GET', '/auth/spotify/callback', { params: {code, state, error}, body: undefined });
}

// GET /auth/spotify/status
export function spotify_auth_status_endpoint_auth_spotify_status_get() {
  return _request('GET', '/auth/spotify/status', { params: undefined, body: undefined });
}

// GET /health
export function health_health_get() {
  return _request('GET', '/health', { params: undefined, body: undefined });
}
